### ISSUE TITLE
Using a custom kernel version

### ISSUE THREAD

**Issue by zeroby0** [p4lang/p4pi#30]
Hii!

Is there a minimum kernel version required to run p4pi?

I'm planning to run a [custom wifi firmware](https://github.com/seemoo-lab/nexmon_csi) which supports only versions 5.4 and 4.19, whereas p4pi iso ships with 5.10. So I would like to either downgrade the kernel or fork the repo and create an ISO with kernel 5.4 (any advice for which would be greately appreciated too :)

Thanks :)

**Comment by rst0git** [comment]
Hi @zeroby0, P4Pi is using DPDK and the kernel requirements are for that are listed [here](https://doc.dpdk.org/guides-18.11/linux_gsg/sys_reqs.html#running-dpdk-applications). You can also build a custom kernel version using the config in https://github.com/p4lang/p4pi/tree/master/p4pi-kernel

**Comment by zeroby0** [comment]
That helps a lot! Thank you! And your documentation is _excellent_!

So if I understand right, I'll have the kernel as a debian package at the end, and to create an iso I can replace `p4pi-linux-image-5.10.52-v8+` with the local .deb file.
