### ISSUE TITLE
Cannot boot a new kernel 

### ISSUE THREAD

**Issue by levaitamas** [p4lang/p4pi#40]
Hi,

I am working on compiling a kernel with BPF modules included for tc and the p4c-ebpf. I am stuck at booting a new kernel.

I was following the p4pi kernel compilation guide at https://github.com/p4lang/p4pi/tree/master/p4pi-kernel/README.md  with the current raspberrypi-linux version (5.10.60) taken from https://github.com/raspberrypi/linux. 

I have the deb packages compiled:
```
-rw-r--r--  1 pi pi  7562092 Aug 24 09:06 p4pi-linux-headers-5.10.60-v8+_5.10.60-v8+-1_arm64.deb
-rw-r--r--  1 pi pi 22517552 Aug 24 09:07 p4pi-linux-image-5.10.60-v8+_5.10.60-v8+-1_arm64.deb
-rw-r--r--  1 pi pi  1118852 Aug 24 09:06 p4pi-linux-libc-dev_5.10.60-v8+-1_arm64.deb
```

However, after installing the image and header packages, the system still boots the old kernel:
```sh
pi@p4pi:~$ uname -a
Linux p4pi 5.10.52-v8+ #1 SMP PREEMPT Sat Aug 7 03:52:12 UTC 2021 aarch64 GNU/Linux
```

Do you have any ideas which step is missing?

Thanks, 
Tamas

**Comment by rst0git** [comment]
@levaitamas By default, the deb packages install the kernel in `/boot/vmlinuz-5.10.60-v8+`, however, Raspberry Pi 4
is using the`kernel8.img` filename on the boot partition when loading the kernel. Thus, you can replace the existing kernel with:
```
sudo mv /boot/vmlinuz-5.10.60-v8+ /boot/kernel8.img
sudo reboot
```

**Comment by levaitamas** [comment]
Thank you, @rst0git! It works.
